language: haskell

notifications:
  recipients:
    - lasse@schuirmann.net
  email:
    on_failure: always
    on_success: change

ghc:
  - 7.6
  - 7.4

install:
  - git clone https://github.com/BNFC/bnfc --depth 1 bnfc
  - cd bnfc/source
  - sudo cabal install
  - cabal update
  - cabal install cabal-install
  - sudo apt-get install libghc-mtl-dev
  - sudo apt-get install libghc-mtl-doc
  - sudo apt-get install libghc-mtl-prof
  - ghc-pkg list mtl
  - cd ../..
  - sudo apt-get install python3
  - git clone https://github.com/coala-analyzer/coala --depth 1 coala
  - cd coala
  - sudo python3 setup.py install
  - cd ..
  - sudo rm -rf bnfc coala

script:
  - sh run_tests.sh
  - coala
