language: haskell

notifications:
  recipients:
    - lasse@schuirmann.net
  email:
    on_failure: always
    on_success: change

ghc:
  - 7.8
  - 7.6
  - 7.4

install:
  - git clone https://github.com/BNFC/bnfc --depth 1 bnfc && cd bnfc/source && sudo cabal install && cd ../..

script:
  - sh run_tests.sh
